#!/bin/bash

# OmniTools Email Service Fix Script
# This script fixes existing OmniTools installations by setting up email service and nginx proxy

set -e

echo "=========================================="
echo "OmniTools Email Service Fix"
echo "=========================================="

# Check if script is run with sudo
if [[ $EUID -ne 0 ]]; then
   echo "❌ This script must be run with sudo"
   exit 1
fi

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo "📁 Working directory: $SCRIPT_DIR"
echo ""

# Detect nginx site name
NGINX_SITE="${NGINX_SITE:-omnitools}"
NGINX_CONF="/etc/nginx/sites-available/${NGINX_SITE}"

if [[ ! -f "${NGINX_CONF}" ]]; then
  echo "⚠️  Nginx site config not found at ${NGINX_CONF}"
  echo "Searching for existing nginx config..."
  FOUND_CONF=$(find /etc/nginx/sites-available -name "*omnitools*" -o -name "*expense*" | head -1)
  if [[ -n "$FOUND_CONF" ]]; then
    NGINX_CONF="$FOUND_CONF"
    echo "Found: ${NGINX_CONF}"
  else
    echo "❌ Could not find nginx config. Using default location: ${NGINX_CONF}"
  fi
fi

# Step 1: Pull latest code
echo "📥 Step 1: Pulling latest code from repository..."
if git pull; then
    echo "✅ Code pulled successfully"
else
    echo "❌ Failed to pull code"
    exit 1
fi
echo ""

# Step 2: Create/Update Email Service
echo "📧 Step 2: Setting up email service (systemd)..."
cat > "/etc/systemd/system/omnitools-email.service" <<'SVCEOF'
[Unit]
Description=OmniTools Email Server
After=network.target
StartLimitInterval=200
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory=APP_DIR_PLACEHOLDER
ExecStart=/usr/bin/node server/send-mail.mjs
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF

# Replace APP_DIR placeholder
sed -i "s|APP_DIR_PLACEHOLDER|${SCRIPT_DIR}|g" /etc/systemd/system/omnitools-email.service
echo "✅ Systemd service created at /etc/systemd/system/omnitools-email.service"
echo ""

# Step 3: Enable and start email service
echo "🚀 Step 3: Starting email service..."
systemctl daemon-reload
systemctl enable omnitools-email
systemctl start omnitools-email
echo "✅ Email service started"

# Check service status
sleep 2
if systemctl is-active --quiet omnitools-email; then
  echo "✅ Email service is running"
else
  echo "⚠️  Email service may not be running. Check with: sudo journalctl -u omnitools-email -n 20"
fi
echo ""

# Step 4: Update nginx configuration
echo "🔧 Step 4: Updating nginx configuration..."

# Backup existing config
if [[ -f "${NGINX_CONF}" ]]; then
  BACKUP_FILE="${NGINX_CONF}.backup.$(date +%s)"
  cp "${NGINX_CONF}" "${BACKUP_FILE}"
  echo "✅ Backed up existing config to: ${BACKUP_FILE}"
fi

# Generate new nginx config
cat > "${NGINX_CONF}" <<'NGXEOF'
# OmniTools — automatically generated by fix-email-service.sh
upstream email_server {
    server 127.0.0.1:3001;
}

server {
    listen 80;
    listen [::]:80;
    server_name _;

    root APPDIR_PLACEHOLDER/dist;
    index index.html;

    add_header X-Content-Type-Options nosniff always;

    # API proxy to email service
    location /api/ {
        proxy_pass http://email_server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_request_buffering off;
        client_max_body_size 100M;
    }

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets caching
    location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
NGXEOF

# Replace app directory placeholder
sed -i "s|APPDIR_PLACEHOLDER|${SCRIPT_DIR}|g" "${NGINX_CONF}"
echo "✅ Nginx configuration updated at: ${NGINX_CONF}"
echo ""

# Step 5: Test nginx config
echo "🧪 Step 5: Testing nginx configuration..."
if nginx -t; then
    echo "✅ Nginx configuration is valid"
else
    echo "❌ Nginx configuration has errors"
    echo "Restoring backup..."
    if [[ -f "${BACKUP_FILE}" ]]; then
      cp "${BACKUP_FILE}" "${NGINX_CONF}"
      systemctl reload nginx
      echo "⚠️  Restored backup and reloaded nginx"
    fi
    exit 1
fi
echo ""

# Step 6: Reload nginx
echo "🔄 Step 6: Reloading nginx..."
if systemctl reload nginx; then
    echo "✅ Nginx reloaded successfully"
else
    echo "❌ Failed to reload nginx"
    exit 1
fi
echo ""

echo "=========================================="
echo "✨ Email service setup completed!"
echo ""
echo "📋 Next steps:"
echo "  1. Verify email service: sudo systemctl status omnitools-email"
echo "  2. Check email logs: sudo journalctl -u omnitools-email -f"
echo "  3. Test email sending in the application"
echo ""
echo "💡 To update in the future, use: sudo bash upgrade.sh"
echo "=========================================="
