/** System category list for expense lines */
export const EXPENSE_CATEGORIES: readonly string[] = [
  "Advertising",
  "Bank fee",
  "Purchase",
  "AP-VENDOR",
  "subcontractor-labour",
  "Business Meals",
  "Dues",
  "IT Hosting fee",
  "Fuel",
  "Accounting & Legal Fees",
  "License Fees",
  "Marketing",
  "Office Supplies",
  "Packing & Freight",
  "Passport fee",
  "Courier & Postage",
  "Printer Cartridges",
  "Printer Paper",
  "Computer Expenses",
  "Computer equipment",
  "Telephones",
  "Tools",
  "Training Fees",
  "Travel",
  "Other",
] as const;
